# -*- coding: utf-8 -*-
"""FinanceAnalyticsProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11RltKjMmBZfVrGhO1ohoarjv6kWS3zKS
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()

from google.colab import files
uploaded = files.upload()

df_cust = pd.read_csv('customers.csv')
df_cust

df_txn = pd.read_csv('finance_transactions.csv')
df_txn

df_cust.info()

df_txn.info()

"""Checking Missing Values"""

df_cust.isnull().sum()

"""Checking full row duplicates"""

df_cust.duplicated().sum()

"""Checking duplicate customer-id"""

df_cust['customer_id'].duplicated().sum()

"""Fixing column typo"""

df_cust = df_cust.rename(columns={'fisrt_name': 'first_name'})

"""Convert date column to datetime"""

df_cust['date_of_birth'] = pd.to_datetime(df_cust['date_of_birth'], format='%d-%m-%Y')
df_cust['join_date'] = pd.to_datetime(df_cust['join_date'], format='%d-%m-%Y')

df_cust.dtypes

"""Looking for spelling errors , casing issues"""

print(df_cust['gender'].unique())
print(df_cust['city'].unique())
print(df_cust['state'].unique())
print(df_cust['occupation'].unique())
print(df_cust['customer_segment'].unique())

"""Calculating customer age and tenure_years from date column"""

from datetime import datetime

today = pd.Timestamp('2026-08-10')

df_cust['age'] = (today - df_cust['date_of_birth']).dt.days // 365
df_cust['tenure_years'] = (today - df_cust['join_date']).dt.days // 365

df_cust[['date_of_birth', 'age', 'join_date', 'tenure_years']].head()

"""finance-transactions ---

Checking missing fee-amount values
"""

df_txn[df_txn['fee_amount'].isnull()]

df_txn['fee_amount'].value_counts().head(10)

"""Filling missing fee amount with 0"""

df_txn['fee_amount'] = df_txn['fee_amount'].fillna(0)

"""Verifying no missing values"""

df_txn['fee_amount'].isnull().sum()

"""Scanning everything"""

df_txn['channel'] = df_txn['channel'].str.strip()

print(df_txn['channel'].unique())
print(df_txn['transaction_type'].unique())
print(df_txn['transaction_status'].unique())
print(df_txn['is_fraud'].unique())
print(df_txn['merchant_category'].unique())

"""Typo"""

df_txn['channel'] = df_txn['channel'].replace('M@bile App', 'Mobile App')

df_txn['channel'].unique()

"""Checking full row duplicates"""

df_txn.duplicated().sum()

"""Checking duplicate transaction id"""

df_txn['transaction_id'].duplicated().sum()

"""Pull out duplicate transactionid rows"""

dup_ids = df_txn[df_txn['transaction_id'].duplicated(keep=False)]
dup_ids.sort_values('transaction_id')

"""Checking the exact conflicting duplicate"""

for tid in dup_ids['transaction_id'].unique():
    subset = df_txn[df_txn['transaction_id'] == tid]
    if not subset.duplicated(keep=False).all():
        print(tid)
        print(subset)

"""Removing the incorrect duplicates"""

df_txn = df_txn.drop(df_txn[(df_txn['transaction_id'] == 'T00000009') & (df_txn['fee_amount'] == 0.00)].index)

"""Removing remaining duplicates"""

df_txn = df_txn.drop_duplicates()

df_txn.shape
print("Remaining duplicate transaction_ids:", df_txn['transaction_id'].duplicated().sum())

"""Converting transactiondate to datetime"""

df_txn['transaction_date'] = pd.to_datetime(df_txn['transaction_date'], format='%d-%m-%Y')

df_txn.dtypes

"""Checking for negative values"""

df_txn[['amount', 'fee_amount', 'tax_amount']].describe()

"""Confirms every customerid exists in transactions"""

orphan_check = ~df_txn['customer_id'].isin(df_cust['customer_id'])
orphan_check.sum()

"""checking negative transaction amounts"""

negative_amounts = df_txn[df_txn['amount'] < 0]
print(negative_amounts.shape)
negative_amounts[['transaction_type', 'amount', 'transaction_status']].head(10)

Fixing -ve

df_txn['amount'] = df_txn['amount'].abs()

verifying min amount to be greater than 0

df_txn['amount'].min()

"""Exporting"""

df_cust.to_csv('customers_cleaned.csv', index=False)
df_txn.to_csv('transactions_cleaned.csv', index=False)

from google.colab import files
files.download('customers_cleaned.csv')
files.download('transactions_cleaned.csv')